CREATE TABLE IF NOT EXISTS ratings (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    spool_id BIGINT NOT NULL,
    rating BIGINT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (spool_id) REFERENCES spools(id) ON DELETE CASCADE
);

---- create above / drop below ----

DROP TABLE IF EXISTS ratings;
