// Package handlers implements the API handlers for the auth server
// This file contains the methods that satisfy the interface generated by OpenAPI
// The actual business logic is delegated to the handlers/ui and handlers/healthchecks packages
package handlers

import (
	"context"
	"errors"

	"github.com/jsnfwlr/filamate/internal/db"
	"github.com/jsnfwlr/filamate/static"
)

type Handlers struct {
	DBClient   *db.Client
	staticPath string
	indexPath  string
	staticFS   static.FS
}

// var tracer = go11y.NewTracer("github.com/jsnfwlr/filamate/internal/server/handlers")

func New(ctx context.Context, dbClient *db.Client, staticType string) (handlers Handlers, fault error) {
	// ctx, o := go11y.Get(ctx)

	if staticType != "embedded" && staticType != "directory" {
		return Handlers{}, errors.New("invalid STATIC_TYPE, must be 'embedded' or 'directory'")
	}

	var err error
	var staticFS static.FS

	staticFS, err = static.NewEmbedded()
	if staticType == "directory" {
		staticFS, err = static.NewDirectory("static")
	}
	if err != nil {
		return Handlers{}, err
	}

	s := Handlers{
		DBClient:   dbClient,
		staticPath: "static",
		indexPath:  "index.html",
		staticFS:   staticFS,
	}
	return s, nil
}
