// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brands.sql

package db

import (
	"context"
)

const createBrand = `-- name: CreateBrand :one
INSERT INTO brands (label, active, store_id) VALUES ($1, $2, $3) RETURNING id, label, active, store_id
`

type CreateBrandParams struct {
	Label   string `json:"label"`
	Active  bool   `json:"active"`
	StoreID *int64 `json:"store_id"`
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, createBrand, arg.Label, arg.Active, arg.StoreID)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Active,
		&i.StoreID,
	)
	return i, err
}

const deleteBrand = `-- name: DeleteBrand :exec
DELETE FROM brands WHERE id = $1
`

func (q *Queries) DeleteBrand(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBrand, id)
	return err
}

const findBrands = `-- name: FindBrands :many
SELECT id, label, active, store_id
    FROM brands
    ORDER BY label ASC
`

func (q *Queries) FindBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.Query(ctx, findBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Brand{}
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Active,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBrandByID = `-- name: GetBrandByID :one
SELECT id, label, active, store_id FROM brands WHERE id = $1
`

func (q *Queries) GetBrandByID(ctx context.Context, id int64) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandByID, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Active,
		&i.StoreID,
	)
	return i, err
}

const updateBrand = `-- name: UpdateBrand :one
UPDATE brands SET label = $1, active = $2, store_id = $3 WHERE id = $4 RETURNING id, label, active, store_id
`

type UpdateBrandParams struct {
	Label  string `json:"label"`
	Active bool   `json:"active"`
	Store  *int64 `json:"store"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, updateBrand,
		arg.Label,
		arg.Active,
		arg.Store,
		arg.ID,
	)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Active,
		&i.StoreID,
	)
	return i, err
}
