// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: colors.sql

package db

import (
	"context"
)

const createColor = `-- name: CreateColor :one
INSERT INTO colors (label, hex_code, alias) VALUES ($1, $2, $3) RETURNING id, label, hex_code, alias
`

type CreateColorParams struct {
	Label   string  `json:"label"`
	HexCode string  `json:"hex_code"`
	Alias   *string `json:"alias"`
}

func (q *Queries) CreateColor(ctx context.Context, arg CreateColorParams) (Color, error) {
	row := q.db.QueryRow(ctx, createColor, arg.Label, arg.HexCode, arg.Alias)
	var i Color
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.HexCode,
		&i.Alias,
	)
	return i, err
}

const deleteColor = `-- name: DeleteColor :exec
DELETE FROM colors WHERE id = $1
`

func (q *Queries) DeleteColor(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteColor, id)
	return err
}

const findColors = `-- name: FindColors :many
SELECT id, label, hex_code, alias FROM colors
`

func (q *Queries) FindColors(ctx context.Context) ([]Color, error) {
	rows, err := q.db.Query(ctx, findColors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Color{}
	for rows.Next() {
		var i Color
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.HexCode,
			&i.Alias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getColorByID = `-- name: GetColorByID :one
SELECT id, label, hex_code, alias FROM colors WHERE id = $1
`

func (q *Queries) GetColorByID(ctx context.Context, id int64) (Color, error) {
	row := q.db.QueryRow(ctx, getColorByID, id)
	var i Color
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.HexCode,
		&i.Alias,
	)
	return i, err
}

const updateColor = `-- name: UpdateColor :one
UPDATE colors SET label = $1, hex_code = $2, alias = $3 WHERE id = $4 RETURNING id, label, hex_code, alias
`

type UpdateColorParams struct {
	Label   string  `json:"label"`
	HexCode string  `json:"hex_code"`
	Alias   *string `json:"alias"`
	ID      int64   `json:"id"`
}

func (q *Queries) UpdateColor(ctx context.Context, arg UpdateColorParams) (Color, error) {
	row := q.db.QueryRow(ctx, updateColor,
		arg.Label,
		arg.HexCode,
		arg.Alias,
		arg.ID,
	)
	var i Color
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.HexCode,
		&i.Alias,
	)
	return i, err
}
