// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: healthcheck.sql

package db

import (
	"context"
)

const checkMigration = `-- name: CheckMigration :one
SELECT version::integer FROM db_version
`

func (q *Queries) CheckMigration(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, checkMigration)
	var version int32
	err := row.Scan(&version)
	return version, err
}
