// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package db

import (
	"context"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (label, description, capacity, printable, tally) VALUES ($1, $2, $3, $4, $5) RETURNING id, label, description, capacity, printable, tally
`

type CreateLocationParams struct {
	Label       string `json:"label"`
	Description string `json:"description"`
	Capacity    int32  `json:"capacity"`
	Printable   bool   `json:"printable"`
	Tally       bool   `json:"tally"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.Label,
		arg.Description,
		arg.Capacity,
		arg.Printable,
		arg.Tally,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Description,
		&i.Capacity,
		&i.Printable,
		&i.Tally,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const findLocations = `-- name: FindLocations :many
SELECT id, label, description, capacity, printable, tally FROM locations
`

func (q *Queries) FindLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, findLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Description,
			&i.Capacity,
			&i.Printable,
			&i.Tally,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, label, description, capacity, printable, tally FROM locations WHERE id = $1
`

func (q *Queries) GetLocationByID(ctx context.Context, id int64) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Description,
		&i.Capacity,
		&i.Printable,
		&i.Tally,
	)
	return i, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations SET label = $1, description = $2, capacity = $3, printable = $4, tally = $5 WHERE id = $6 RETURNING id, label, description, capacity, printable, tally
`

type UpdateLocationParams struct {
	Label       string `json:"label"`
	Description string `json:"description"`
	Capacity    int32  `json:"capacity"`
	Printable   bool   `json:"printable"`
	Tally       bool   `json:"tally"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.Label,
		arg.Description,
		arg.Capacity,
		arg.Printable,
		arg.Tally,
		arg.ID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Description,
		&i.Capacity,
		&i.Printable,
		&i.Tally,
	)
	return i, err
}
