// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: materials.sql

package db

import (
	"context"
)

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO materials (label, class, description, special) VALUES ($1, $2, $3, $4) RETURNING id, label, class, description, special
`

type CreateMaterialParams struct {
	Label       string `json:"label"`
	Class       string `json:"class"`
	Description string `json:"description"`
	Special     bool   `json:"special"`
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error) {
	row := q.db.QueryRow(ctx, createMaterial,
		arg.Label,
		arg.Class,
		arg.Description,
		arg.Special,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Class,
		&i.Description,
		&i.Special,
	)
	return i, err
}

const deleteMaterial = `-- name: DeleteMaterial :exec
DELETE FROM materials WHERE id = $1
`

func (q *Queries) DeleteMaterial(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMaterial, id)
	return err
}

const findMaterials = `-- name: FindMaterials :many
SELECT id, label, class, description, special FROM materials ORDER BY label ASC
`

func (q *Queries) FindMaterials(ctx context.Context) ([]Material, error) {
	rows, err := q.db.Query(ctx, findMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Material{}
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Class,
			&i.Description,
			&i.Special,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterialByID = `-- name: GetMaterialByID :one
SELECT id, label, class, description, special FROM materials WHERE id = $1
`

func (q *Queries) GetMaterialByID(ctx context.Context, id int64) (Material, error) {
	row := q.db.QueryRow(ctx, getMaterialByID, id)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Class,
		&i.Description,
		&i.Special,
	)
	return i, err
}

const updateMaterial = `-- name: UpdateMaterial :one
UPDATE materials SET label = $1, class = $2, description = $3, special = $4 WHERE id = $5 RETURNING id, label, class, description, special
`

type UpdateMaterialParams struct {
	Label       string `json:"label"`
	Class       string `json:"class"`
	Description string `json:"description"`
	Special     bool   `json:"special"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) (Material, error) {
	row := q.db.QueryRow(ctx, updateMaterial,
		arg.Label,
		arg.Class,
		arg.Description,
		arg.Special,
		arg.ID,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Class,
		&i.Description,
		&i.Special,
	)
	return i, err
}
