// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// Table storing information about filament brands
type Brand struct {
	ID int64 `json:"id"`
	// The brand name (e.g. Prusament, Anycubic, Sunlu, etc.)
	Label string `json:"label"`
	// Whether or not the brand is still in business
	Active bool `json:"active"`
	// Does the brand have a primary store where their filament is sold?
	StoreID *int64 `json:"store_id"`
}

// Table storing information about filament colors
type Color struct {
	ID int64 `json:"id"`
	// The name of the color (e.g. "Red", "Blue", "Transparent", etc.)
	Label string `json:"label"`
	// The hexadecimal color code (e.g. "#FF0000" for red)
	HexCode string `json:"hex_code"`
	// An alternative name for the color (e.g. "Crimson Red" for "#DC143C")
	Alias *string `json:"alias"`
}

type DbVersion struct {
	Version int32 `json:"version"`
}

// Table storing information about filament storage locations
type Location struct {
	ID int64 `json:"id"`
	// The name of the storage location (e.g. Shelf A, Box 1, Drawer 3, etc.)
	Label string `json:"label"`
	// A more detailed explanation of the storage location (e.g. "Top shelf in the closet", "Plastic box under the desk", etc.)
	Description string `json:"description"`
	// The maximum number of spools that can be stored in this location
	Capacity int32 `json:"capacity"`
	// Whether this storage location is printable (i.e. is attached to or part of a 3D printer)
	Printable bool `json:"printable"`
	// Should this location be included in spool tallies?
	Tally bool `json:"tally"`
}

// Table storing information about filament materials
type Material struct {
	ID int64 `json:"id"`
	// The detailed name of the material (e.g. Basic PLA, Hyper PLA, PETG, TPU 85A PLA+ etc.)
	Label string `json:"label"`
	// The material class/type (e.g. PLA, PETG, TPU, ABS, etc.)
	Class string `json:"class"`
	// The common name of the material (e.g. PLA, Hyper PLA, PETG, TPU 85A PLA+, etc.)
	Description string `json:"description"`
	// Is this a special material (e.g. composite filaments with wood, metal, or carbon fiber additives)?
	Special bool `json:"special"`
}

// Table storing information about individual filament spools
type Spool struct {
	ID         int64 `json:"id"`
	MaterialID int64 `json:"material_id"`
	BrandID    int64 `json:"brand_id"`
	LocationID int64 `json:"location_id"`
	StoreID    int64 `json:"store_id"`
	// The marketed weight of the just filament on the spool in grams
	Weight pgtype.Numeric `json:"weight"`
	// The initial, packaged weight of the both the filament and the spool in grams
	CombinedWeight pgtype.Numeric `json:"combined_weight"`
	// The current weight of the both the filament and the spool in grams
	CurrentWeight pgtype.Numeric `json:"current_weight"`
	// The cost of the filament at the time of purchase
	Price pgtype.Numeric `json:"price"`
	// Whether the spool is empty
	Empty bool `json:"empty"`
	// The timestamp when the spool record was created
	CreatedAt time.Time `json:"created_at"`
	// The timestamp when the spool record was last updated
	UpdatedAt time.Time `json:"updated_at"`
	// The timestamp when the spool record was deleted (soft delete)
	DeletedAt *time.Time `json:"deleted_at"`
}

// Associative table linking spools to their colors (many-to-many relationship)
type SpoolColor struct {
	ID      int64 `json:"id"`
	SpoolID int64 `json:"spool_id"`
	ColorID int64 `json:"color_id"`
}

// Table storing information about stores where filament was purchased
type Store struct {
	ID int64 `json:"id"`
	// The name of the store (e.g. Prusament, Amazon, etc.)
	Label string `json:"label"`
	// The URL of the store's website (e.g. https://www.ebay.com/)
	URL *string `json:"url"`
}
