// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddSpoolColors(ctx context.Context, spoolID int64, colorIds []int64) error
	CheckDemoData(ctx context.Context) (bool, error)
	CheckMigration(ctx context.Context) (int32, error)
	CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error)
	CreateColor(ctx context.Context, arg CreateColorParams) (Color, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error)
	CreateRating(ctx context.Context, rating int64, spoolID int64) (Rating, error)
	CreateSpool(ctx context.Context, arg CreateSpoolParams) (Spool, error)
	CreateStore(ctx context.Context, label string, uRL *string) (Store, error)
	DeleteBrand(ctx context.Context, id int64) error
	DeleteColor(ctx context.Context, id int64) error
	DeleteLocation(ctx context.Context, id int64) error
	DeleteMaterial(ctx context.Context, id int64) error
	DeleteRating(ctx context.Context, id int64) error
	DeleteSpool(ctx context.Context, id int64) error
	DeleteStore(ctx context.Context, id int64) error
	FindBrands(ctx context.Context) ([]Brand, error)
	FindColors(ctx context.Context) ([]Color, error)
	FindLocations(ctx context.Context) ([]Location, error)
	FindMaterials(ctx context.Context) ([]Material, error)
	FindRatings(ctx context.Context) ([]Rating, error)
	FindSpools(ctx context.Context) ([]Spool, error)
	FindStores(ctx context.Context) ([]Store, error)
	GetBrandByID(ctx context.Context, id int64) (Brand, error)
	GetColorByID(ctx context.Context, id int64) (Color, error)
	GetLocationByID(ctx context.Context, id int64) (Location, error)
	GetMaterialByID(ctx context.Context, id int64) (Material, error)
	// GetMaterialChartData returns the data for a material chart: class, material, brand, and count of spools for each combo.
	// It includes a total row for each class, class and material, and a grand total row. The results are ordered by material label and class, with null values treated as 'All'.
	GetMaterialChartData(ctx context.Context) ([]GetMaterialChartDataRow, error)
	GetRatingByID(ctx context.Context, id int64) (Rating, error)
	// GetRatingStats returns the average rating for each brand and material combination, along with the count of ratings.
	// It orders the results by average rating in descending order, and then by brand and material labels in ascending order.
	GetRatingStats(ctx context.Context) ([]GetRatingStatsRow, error)
	GetRatingsByBrandIDAndMaterialID(ctx context.Context, brandID int64, materialID int64) ([]Rating, error)
	GetSpoolByID(ctx context.Context, id int64) (Spool, error)
	GetSpoolColors(ctx context.Context, spoolID int64) ([]Color, error)
	// GetStorageStats returns the storage statistics for each location, including the maximum capacity, used capacity, and free capacity. It also includes a total row that sums up the statistics for all locations. The results are ordered by location ID.
	GetStorageStats(ctx context.Context) ([]GetStorageStatsRow, error)
	GetStoreByID(ctx context.Context, id int64) (Store, error)
	// GetUsageStats returns the most used color and material combinations, sorted by the number of empty spools and total spools. It filters out combinations that have only one spool or where the number of empty spools is less than half of the total spools.
	GetUsageStats(ctx context.Context) ([]GetUsageStatsRow, error)
	ResetSpoolColor(ctx context.Context, spoolID int64) error
	SetDemoData(ctx context.Context) error
	UpdateBrand(ctx context.Context, arg UpdateBrandParams) (Brand, error)
	UpdateColor(ctx context.Context, arg UpdateColorParams) (Color, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) (Material, error)
	UpdateRating(ctx context.Context, rating int64, iD int64) (Rating, error)
	UpdateSpool(ctx context.Context, arg UpdateSpoolParams) (Spool, error)
	UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error)
}

var _ Querier = (*Queries)(nil)
