// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddSpoolColors(ctx context.Context, spoolID int64, colorIds []int64) error
	CheckMigration(ctx context.Context) (int32, error)
	CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error)
	CreateColor(ctx context.Context, arg CreateColorParams) (Color, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error)
	CreateSpool(ctx context.Context, arg CreateSpoolParams) (Spool, error)
	CreateStore(ctx context.Context, label string, uRL *string) (Store, error)
	DeleteBrand(ctx context.Context, id int64) error
	DeleteColor(ctx context.Context, id int64) error
	DeleteLocation(ctx context.Context, id int64) error
	DeleteMaterial(ctx context.Context, id int64) error
	DeleteSpool(ctx context.Context, id int64) error
	DeleteStore(ctx context.Context, id int64) error
	FindBrands(ctx context.Context) ([]Brand, error)
	FindColors(ctx context.Context) ([]Color, error)
	FindLocations(ctx context.Context) ([]Location, error)
	FindMaterials(ctx context.Context) ([]Material, error)
	FindSpools(ctx context.Context) ([]Spool, error)
	FindStores(ctx context.Context) ([]Store, error)
	GetBrandByID(ctx context.Context, id int64) (Brand, error)
	GetColorByID(ctx context.Context, id int64) (Color, error)
	GetLocationByID(ctx context.Context, id int64) (Location, error)
	GetMaterialByID(ctx context.Context, id int64) (Material, error)
	GetSpoolByID(ctx context.Context, id int64) (Spool, error)
	GetSpoolColors(ctx context.Context, spoolID int64) ([]Color, error)
	// GetStorageStats returns the storage statistics for each location, including the maximum capacity, used capacity, and free capacity. It also includes a total row that sums up the statistics for all locations. The results are ordered by location ID.
	GetStorageStats(ctx context.Context) ([]GetStorageStatsRow, error)
	GetStoreByID(ctx context.Context, id int64) (Store, error)
	// GetUsageStats returns the most used color and material combinations, sorted by the number of empty spools and total spools. It filters out combinations that have only one spool or where the number of empty spools is less than half of the total spools.
	GetUsageStats(ctx context.Context) ([]GetUsageStatsRow, error)
	ResetSpoolColor(ctx context.Context, spoolID int64) error
	UpdateBrand(ctx context.Context, arg UpdateBrandParams) (Brand, error)
	UpdateColor(ctx context.Context, arg UpdateColorParams) (Color, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) (Material, error)
	UpdateSpool(ctx context.Context, arg UpdateSpoolParams) (Spool, error)
	UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error)
}

var _ Querier = (*Queries)(nil)
