// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ratings.sql

package db

import (
	"context"
)

const createRating = `-- name: CreateRating :one
INSERT INTO ratings (rating, spool_id) VALUES ($1::bigint, $2) RETURNING id, spool_id, rating, created_at, updated_at
`

func (q *Queries) CreateRating(ctx context.Context, rating int64, spoolID int64) (Rating, error) {
	row := q.db.QueryRow(ctx, createRating, rating, spoolID)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.SpoolID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRating = `-- name: DeleteRating :exec
DELETE FROM ratings WHERE id = $1
`

func (q *Queries) DeleteRating(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRating, id)
	return err
}

const findRatings = `-- name: FindRatings :many
SELECT ratings.id, ratings.spool_id, ratings.rating, ratings.created_at, ratings.updated_at
FROM ratings
JOIN spools ON spools.id = ratings.spool_id
JOIN brands ON brands.id = spools.brand_id
JOIN materials ON materials.id = spools.material_id
WHERE spools.deleted_at IS NULL
ORDER BY brands.label, materials.label ASC
`

func (q *Queries) FindRatings(ctx context.Context) ([]Rating, error) {
	rows, err := q.db.Query(ctx, findRatings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rating{}
	for rows.Next() {
		var i Rating
		if err := rows.Scan(
			&i.ID,
			&i.SpoolID,
			&i.Rating,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRatingByID = `-- name: GetRatingByID :one
SELECT id, spool_id, rating, created_at, updated_at FROM ratings WHERE id = $1
`

func (q *Queries) GetRatingByID(ctx context.Context, id int64) (Rating, error) {
	row := q.db.QueryRow(ctx, getRatingByID, id)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.SpoolID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRatingsByBrandIDAndMaterialID = `-- name: GetRatingsByBrandIDAndMaterialID :many
SELECT ratings.id, ratings.spool_id, ratings.rating, ratings.created_at, ratings.updated_at
FROM ratings
JOIN spools ON spools.id = ratings.spool_id
JOIN brands ON brands.id = spools.brand_id
JOIN materials ON materials.id = spools.material_id
WHERE spools.brand_id = $1
AND spools.material_id = $2
AND spools.deleted_at IS NULL
`

func (q *Queries) GetRatingsByBrandIDAndMaterialID(ctx context.Context, brandID int64, materialID int64) ([]Rating, error) {
	rows, err := q.db.Query(ctx, getRatingsByBrandIDAndMaterialID, brandID, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rating{}
	for rows.Next() {
		var i Rating
		if err := rows.Scan(
			&i.ID,
			&i.SpoolID,
			&i.Rating,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRating = `-- name: UpdateRating :one
UPDATE ratings SET rating = $1::bigint, updated_at = NOW() WHERE id = $2 RETURNING id, spool_id, rating, created_at, updated_at
`

func (q *Queries) UpdateRating(ctx context.Context, rating int64, iD int64) (Rating, error) {
	row := q.db.QueryRow(ctx, updateRating, rating, iD)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.SpoolID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
