// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spools.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSpoolColors = `-- name: AddSpoolColors :exec
WITH color_set AS (
    SELECT jsonb_array_elements(to_jsonb($2::bigint[]))::bigint as color_values
)
INSERT INTO spool_colors (spool_id, color_id)
SELECT $1, color_values::bigint
FROM color_set
`

func (q *Queries) AddSpoolColors(ctx context.Context, spoolID int64, colorIds []int64) error {
	_, err := q.db.Exec(ctx, addSpoolColors, spoolID, colorIds)
	return err
}

const createSpool = `-- name: CreateSpool :one
INSERT INTO spools (location_id, material_id, brand_id, store_id, emptied_at, weight, combined_weight, current_weight, price) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, material_id, brand_id, location_id, store_id, weight, combined_weight, current_weight, price, created_at, updated_at, deleted_at, emptied_at
`

type CreateSpoolParams struct {
	Location       int64          `json:"location"`
	Material       int64          `json:"material"`
	Brand          int64          `json:"brand"`
	Store          int64          `json:"store"`
	EmptiedAt      *time.Time     `json:"emptied_at"`
	Weight         pgtype.Numeric `json:"weight"`
	CombinedWeight pgtype.Numeric `json:"combined_weight"`
	CurrentWeight  pgtype.Numeric `json:"current_weight"`
	Price          pgtype.Numeric `json:"price"`
}

func (q *Queries) CreateSpool(ctx context.Context, arg CreateSpoolParams) (Spool, error) {
	row := q.db.QueryRow(ctx, createSpool,
		arg.Location,
		arg.Material,
		arg.Brand,
		arg.Store,
		arg.EmptiedAt,
		arg.Weight,
		arg.CombinedWeight,
		arg.CurrentWeight,
		arg.Price,
	)
	var i Spool
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.BrandID,
		&i.LocationID,
		&i.StoreID,
		&i.Weight,
		&i.CombinedWeight,
		&i.CurrentWeight,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmptiedAt,
	)
	return i, err
}

const deleteSpool = `-- name: DeleteSpool :exec
UPDATE spools SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteSpool(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSpool, id)
	return err
}

const findSpools = `-- name: FindSpools :many
SELECT id, material_id, brand_id, location_id, store_id, weight, combined_weight, current_weight, price, created_at, updated_at, deleted_at, emptied_at FROM spools WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) FindSpools(ctx context.Context) ([]Spool, error) {
	rows, err := q.db.Query(ctx, findSpools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spool{}
	for rows.Next() {
		var i Spool
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.BrandID,
			&i.LocationID,
			&i.StoreID,
			&i.Weight,
			&i.CombinedWeight,
			&i.CurrentWeight,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EmptiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpoolByID = `-- name: GetSpoolByID :one
SELECT id, material_id, brand_id, location_id, store_id, weight, combined_weight, current_weight, price, created_at, updated_at, deleted_at, emptied_at FROM spools WHERE id = $1
`

func (q *Queries) GetSpoolByID(ctx context.Context, id int64) (Spool, error) {
	row := q.db.QueryRow(ctx, getSpoolByID, id)
	var i Spool
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.BrandID,
		&i.LocationID,
		&i.StoreID,
		&i.Weight,
		&i.CombinedWeight,
		&i.CurrentWeight,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmptiedAt,
	)
	return i, err
}

const getSpoolColors = `-- name: GetSpoolColors :many
SELECT colors.id, colors.label, colors.hex_code, colors.alias FROM colors JOIN spool_colors ON colors.id = spool_colors.color_id WHERE spool_colors.spool_id = $1
`

func (q *Queries) GetSpoolColors(ctx context.Context, spoolID int64) ([]Color, error) {
	rows, err := q.db.Query(ctx, getSpoolColors, spoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Color{}
	for rows.Next() {
		var i Color
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.HexCode,
			&i.Alias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetSpoolColor = `-- name: ResetSpoolColor :exec
DELETE FROM spool_colors WHERE spool_id = $1
`

func (q *Queries) ResetSpoolColor(ctx context.Context, spoolID int64) error {
	_, err := q.db.Exec(ctx, resetSpoolColor, spoolID)
	return err
}

const updateSpool = `-- name: UpdateSpool :one
UPDATE spools SET location_id = $1, material_id = $2, brand_id = $3, store_id = $4, emptied_at = $5, weight = $6, combined_weight = $7, current_weight = $8, price = $9, updated_at = NOW() WHERE id = $10 RETURNING id, material_id, brand_id, location_id, store_id, weight, combined_weight, current_weight, price, created_at, updated_at, deleted_at, emptied_at
`

type UpdateSpoolParams struct {
	Location       int64          `json:"location"`
	Material       int64          `json:"material"`
	Brand          int64          `json:"brand"`
	Store          int64          `json:"store"`
	EmptiedAt      *time.Time     `json:"emptied_at"`
	Weight         pgtype.Numeric `json:"weight"`
	CombinedWeight pgtype.Numeric `json:"combined_weight"`
	CurrentWeight  pgtype.Numeric `json:"current_weight"`
	Price          pgtype.Numeric `json:"price"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateSpool(ctx context.Context, arg UpdateSpoolParams) (Spool, error) {
	row := q.db.QueryRow(ctx, updateSpool,
		arg.Location,
		arg.Material,
		arg.Brand,
		arg.Store,
		arg.EmptiedAt,
		arg.Weight,
		arg.CombinedWeight,
		arg.CurrentWeight,
		arg.Price,
		arg.ID,
	)
	var i Spool
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.BrandID,
		&i.LocationID,
		&i.StoreID,
		&i.Weight,
		&i.CombinedWeight,
		&i.CurrentWeight,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmptiedAt,
	)
	return i, err
}
