// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stores.sql

package db

import (
	"context"
)

const createStore = `-- name: CreateStore :one
INSERT INTO stores (label, url) VALUES ($1, $2) RETURNING id, label, url
`

func (q *Queries) CreateStore(ctx context.Context, label string, uRL *string) (Store, error) {
	row := q.db.QueryRow(ctx, createStore, label, uRL)
	var i Store
	err := row.Scan(&i.ID, &i.Label, &i.URL)
	return i, err
}

const deleteStore = `-- name: DeleteStore :exec
DELETE FROM stores WHERE id = $1
`

func (q *Queries) DeleteStore(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteStore, id)
	return err
}

const findStores = `-- name: FindStores :many
SELECT id, label, url FROM stores ORDER BY label ASC
`

func (q *Queries) FindStores(ctx context.Context) ([]Store, error) {
	rows, err := q.db.Query(ctx, findStores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(&i.ID, &i.Label, &i.URL); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreByID = `-- name: GetStoreByID :one
SELECT id, label, url FROM stores WHERE id = $1
`

func (q *Queries) GetStoreByID(ctx context.Context, id int64) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByID, id)
	var i Store
	err := row.Scan(&i.ID, &i.Label, &i.URL)
	return i, err
}

const updateStore = `-- name: UpdateStore :one
UPDATE stores SET label = $1, url = $2 WHERE id = $3 RETURNING id, label, url
`

type UpdateStoreParams struct {
	Label string  `json:"label"`
	URL   *string `json:"url"`
	ID    int64   `json:"id"`
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStore, arg.Label, arg.URL, arg.ID)
	var i Store
	err := row.Scan(&i.ID, &i.Label, &i.URL)
	return i, err
}
